import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { url } from "inspector";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shubh Mehrotra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{
      scrollbarWidth: "none",
      overflowX: "hidden",
      cursor: 'url("/icons/cursor.png"), auto',
    }}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
